name: 1.$(Rev:r)
trigger:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  - name: tag
    value: '$(Build.BuildNumber)'

steps:
  - task: Docker@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))  
    displayName: Build And Push
    inputs:
      containerRegistry: 'AzureRegistry'
      repository: 'hunting-owl-charities-dev'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Ho.Charity/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/'
      tags: |
        $(tag)
        latest

  - task: Docker@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Build And Push
    inputs:
      containerRegistry: 'AzureRegistry'
      repository: 'hunting-owl-charities'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Ho.Charity/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/'
      tags: |
        $(tag)
        latest